import { CalculateRequest, Region, REGION_LABELS } from "@/lib/types";
import { Info, MapPin, Users } from "lucide-react";

interface StepProps {
  data: CalculateRequest;
  updateData: (fields: Partial<CalculateRequest>) => void;
}

export default function StepWorkforce({ data, updateData }: StepProps) {
  return (
    <div className="animate-fade-in stagger-children">
      <h2 style={{ fontSize: "1.5rem", marginBottom: 8 }}>Workforce & Location</h2>
      <p style={{ color: "var(--text-secondary)", marginBottom: 24 }}>
        These details determine your eligibility for Mega Project bonuses, Electricity Duty exemptions, and Land Subsidies.
      </p>

      <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
        <div className="card" style={{ padding: 20, display: "flex", flexDirection: "column" }}>
          <div>
            <div style={{ display: "flex", gap: 12, alignItems: "flex-start", marginBottom: 16 }}>
              <div style={{ color: "var(--accent-primary)", marginTop: 2 }}><Users size={20} /></div>
              <div>
                <label className="label" style={{ marginBottom: 4, fontSize: "1rem", color: "var(--text-primary)" }}>Total Employment Count</label>
                <div style={{ fontSize: "0.85rem", color: "var(--text-secondary)" }}>
                  Direct employment generated by the unit.
                </div>
              </div>
            </div>
            <input
              type="number"
              className="input-field"
              value={data.employment_count || ""}
              onChange={(e) => updateData({ employment_count: Number(e.target.value) })}
              min="0"
              placeholder="e.g. 500"
            />
          </div>
          <div style={{ fontSize: "0.8rem", color: "var(--text-tertiary)", display: "flex", gap: 6, marginTop: "auto", paddingTop: 16, padding: "8px 12px", background: "var(--bg-tertiary)", borderRadius: "var(--radius-sm)" }}>
            <Info size={14} style={{ flexShrink: 0, marginTop: 2 }} />
            <span>3,000+ employees required to unlock the Mega Project Bonus (if Fixed Capital Investment ≥ ₹1000 Cr).</span>
          </div>
        </div>

        <div className="card" style={{ padding: 20, display: "flex", flexDirection: "column" }}>
          <div style={{ display: "flex", gap: 12, alignItems: "flex-start", marginBottom: 16 }}>
            <div style={{ color: "var(--accent-primary)", marginTop: 2 }}><MapPin size={20} /></div>
            <div>
              <label className="label" style={{ marginBottom: 4, fontSize: "1rem", color: "var(--text-primary)" }}>Region of Operation</label>
              <div style={{ fontSize: "0.85rem", color: "var(--text-secondary)" }}>
                Select where your unit is located in UP.
              </div>
            </div>
          </div>
          
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {(Object.keys(REGION_LABELS) as Region[]).map((region) => (
              <label
                key={region}
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: 10,
                  padding: "10px 14px",
                  border: "1px solid",
                  borderColor: data.region === region ? "var(--accent-primary)" : "var(--border-primary)",
                  background: data.region === region ? "var(--bg-accent)" : "transparent",
                  borderRadius: "var(--radius-md)",
                  cursor: "pointer",
                  transition: "all 0.2s ease",
                }}
              >
                <input
                  type="radio"
                  name="region"
                  value={region}
                  checked={data.region === region}
                  onChange={() => updateData({ region })}
                  style={{ accentColor: "var(--accent-primary)", width: 16, height: 16 }}
                />
                <span style={{ fontSize: "0.95rem", fontWeight: data.region === region ? 500 : 400 }}>
                  {REGION_LABELS[region]}
                </span>
              </label>
            ))}
          </div>
          
          <div style={{ fontSize: "0.8rem", color: "var(--text-tertiary)", display: "flex", gap: 6, marginTop: "auto", paddingTop: 16, padding: "8px 12px", background: "var(--bg-tertiary)", borderRadius: "var(--radius-sm)" }}>
            <Info size={14} style={{ flexShrink: 0, marginTop: 2 }} />
            <span>Determines the rate for Electricity Duty Exemption (50% to 100%) and Land Subsidy (25% or 50%).</span>
          </div>
        </div>
      </div>
    </div>
  );
}
